apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: discodata-back-public-dev
  name: discodata-back-public-dev
  namespace: discodata
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  selector:
    matchLabels:
      app: discodata-back-public-dev
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: discodata-back-public-dev
    spec:
      containers:
      - env:
        image: txalaparta/disco-data-api_dev_bm:latest
        imagePullPolicy: Always
        name: discodata-back-public-dev
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
