name: Public API Development
# only trigger on pull request closed events
on:
  push:
    branches: [ "main" ]
    paths:
      - back/private/**    
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build the Docker image
      working-directory:  back/
      run: docker build -f private/Dockerfile  --build-arg ENVIRONMENT=prod  -t txalaparta/discodata-private_api_prod:latest .

    - uses: docker/login-action@v3
      name: Login to Docker Hub      
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - uses: actions/checkout@v4
    - name: Push
      working-directory: back/private
      run: docker push txalaparta/discodata-private_api_prod:latest

    - uses: actions/checkout@v4
    - name: Remove the Docker image to free space
      working-directory: back
      run: docker image rmi -f txalaparta/discodata-private_api_prod:latest
